#!/bin/bash
# -*- sh -*-

: << =cut

=head1 NAME

ADB temperatures - Plugin to monitor the Andorid temperatures.

=head1 AUTHOR

Marcin Depa <m.depa91@gmail.com>

=head1 LICENSE

GPLv2

=head1 MAGICK MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. "$MUNIN_LIBDIR/plugins/plugin.sh"

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "suggest" ]; then
        COMMAND='find /sys/class/thermal/thermal_zone*/ -type f -name "type" -exec sh -c '"'"'echo -e $(cat $1):\\t$(cat $(dirname $1)/temp)'"'"' sh {} \;'
        echo $COMMAND
        adb shell "$COMMAND"
        exit 0
fi

declare -A thermal_map

# Populate the array with thermal types and their dividers to calculate degrees of celcius, run 'munin-run adb_temperature suggest' to get raw values
thermal_map=(
    ["bms"]=1000
    ["chg_therm"]=1
    ["xo_therm"]=1
    ["pm8953_tz"]=1000
    ["front_temp"]=1000
    ["back_temp"]=1000
    ["battery"]=1000
)


all_values=$(adb shell 'cat /sys/class/thermal/thermal_zone*/type /sys/class/thermal/thermal_zone*/temp')
lines_len=$(echo "$all_values" | wc -l)
half_len=$((lines_len / 2))

types=$(echo "$all_values" | head -n $half_len)
temperatures=$(echo "$all_values" | tail -n $half_len)
declare -A arr
for i in  $(seq 1 $half_len); do
        type=$(echo "$types" | sed -n "$i"p)
        temperature=$(echo "$temperatures" | sed -n "$i"p)
        if [ -z "$temperature" ]; then
                continue
        fi
        if [[ "$type" == "tsens_tz_sensor"* ]]; then
                continue
        fi
        arr[$type]=$temperature
done

if [ "$1" = "config" ]; then
        echo 'graph_title ADB temperatures'
        echo 'graph_vlabel °C'
        echo 'graph_scale no'
        echo 'graph_category sensors'
        echo 'graph_info Temperatures of connected Android phone using ADB.'
        for key in "${!arr[@]}"; do
                type=$key
                echo "$type.label $type"
        done
        exit 0
fi

for key in "${!arr[@]}"; do
        type=$key
        temp=${arr[$key]}
        divider=${thermal_map[$type]}
        if [[ -z $divider ]]; then
                continue
        fi
        temp_in_celcius=$(( temp / divider ))
        echo "$type.value $temp_in_celcius"
done
